//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanillaAlumnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notas
    {
        public int Id { get; set; }
        public int IdAlumnoMateria { get; set; }
        public int Examen1 { get; set; }
        public int Recuperatorio1 { get; set; }
        public int Examen2 { get; set; }
        public int Recupetario2 { get; set; }
        public int Examen3 { get; set; }
        public int Recuperatorio3 { get; set; }
        public int NotaFinal { get; set; }
        public int ExamenFinal { get; set; }
        public Nullable<bool> Aprobada { get; set; }
    
        public virtual AlumnoMateria AlumnoMateria { get; set; }
    }
}
